export const gameDevProjects = {
  "the-shifter": {
    projectName: "The Shifter",
    linkText: "Link",
    link: "https://team-hustle.itch.io/the-shifter",
    role: ["Lead Programmer", "Project Manager"],
    genre: ["Puzzle", "Platformer", "Combat"],
    developmentTools: ["Unreal Engine 5", "Blender"],
    keyFeatures: [
      "Single Player",
      "2D ⇋ 3D Platformer",
      "Platformer Mechanics",
    ],
    description:
      "You are a a knight trying to escape a castle and the only way to escape is to find the spells and cast shadow puppets so you can traverse the walls, and solve puzzles to escape the horrid place! The game involves you having to transform between the 3D and 2D world where you are once a knight that can turn into shadow animals.",
    tags: ["Unreal Engine", "Game Jam", "3-Person Team"],
    cardImgSrc: "/game-dev-projects/shifter2.png",
    mediaContent: [
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    coreMechanicsContent: [
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    summary:
      "Created in just two weeks for the PirateSoftware Game Jam, The Shifter was built around the theme, 'Shadow and Alchemy.' Set in a haunting castle, the game challenges players to escape using shadow puppet magic—transforming into animals on the walls to solve intricate puzzles. Each transformation unlocks new paths, powers, exploration, and creative problem-solving.",
    designGoals: [
      "Support Seamless Transformation Mechanics",
      "Integrate Shadow-Based Mechanics Deeply Into Level Design",
      "Balance Puzzle-Solving with Platforming",
      "Encourage Creative Puzzle-Solving",
    ],
    coreMechanic: [
      "Led a team of three, organizing workflow over a two-week development cycle using Trello to effectively manage tasks and deadlines",
      "Learned and applied Blender to model and texture 3D assets, significantly contributing to the game’s visual depth and immersion",
      "Designed levels and puzzles that highlighted each shadow animal’s unique abilities, ensuring their mechanics were meaningfully integrated into gameplay",
      "Developed and implemented the transformation mechanic across both 2D and 3D spaces, enabling seamless transitions between gameplay modes",
    ],

    whatWentWell: [
      "Smooth transitions between the 3D and 2D worlds using shadow puppetry mechanics",
      "Strong visual integration of art assets that captured the eerie, shadowy castle atmosphere",
      "Effective communication and teamwork among all three members, allowing us to complete the project smoothly within two weeks",
    ],

    challenges: [
      "Performance issues during the build process, including major lag spikes and occasional crashes",
      "Defining a realistic project scope for a team of three within the two-week time constraint",
      "Level designs could have better leveraged each animal’s abilities to create more engaging puzzle scenarios",
    ],

    lessonsLearned: [
      "Improved my skills in Blender to design and integrate art assets into the game",
      "Developed a clearer grasp of the full game development workflow and the importance of documentation",
      "Learned how to manage a small team effectively and maintain steady progress under tight deadlines",
    ],


  },

  "beetle-bistro": {
    projectName: "Beetle Bistro",
    linkText: "Link to game",
    link: "https://github.com/AashishSubramanian26",
    role: ["Game Developer"],
    genre: ["Party", "Puzzle", "Multiplayer"],
    developmentTools: ["Unity"],
    keyFeatures: [
      "Exploration and puzzle-solving",
      "Space-themed environments",
      "Engaging narrative",
    ],
    description:
      "description ecnldcm ldemclekdcm elkdcm elkdcm ledkcm eldkc meldkmc lked clke",
    tags: ["adventure", "space", "single-player"],
    cardImgSrc: "/game-dev-projects/beetle-bistro2.png",
    mediaContent: [
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    coreMechanicsContent: [
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    summary:
      "Beetle Bistro is an adventure game set in space, where players explore a vibrant, otherworldly environment while solving intricate puzzles. Developed with Unity, the game offers an engaging single-player experience with a space-themed world full of mysteries and challenges. Players take on the role of a resourceful beetle who must navigate through a variety of environments, each with its own set of puzzles. The game emphasizes exploration, puzzle-solving, and a captivating narrative that drives the player's journey. Players uncover secrets, face obstacles, and piece together a story that adds depth to the gameplay experience.",
    designGoals: [
      "Create a captivating and immersive space world.",
      "Incorporate meaningful puzzle mechanics.",
      "Develop a strong narrative that ties gameplay elements together.",
    ],
    coreMechanic: [
      " ", 
      " ", 
      " "],
    whatWentWell: [
      "Puzzle mechanics were intuitive and rewarding.",
      "The narrative resonated well with players.",
    ],
    challenges: [
      "Creating a balance between exploration and puzzle difficulty.",
      "Ensuring smooth player progression through the puzzles.",
    ],
    lessonsLearned: [
      "Narrative-driven gameplay needs to be tied closely with mechanics.",
      "Player progression should be gradual and rewarding.",
    ],
  },
  "midnight-cram": {
    projectName: "The Midnight Cram",
    linkText: "Link",
    link: "https://aashish-subramanian.itch.io/the-midnight-cram",
    role: ["Programmer"],
    genre: ["Horror", "Action", "Singleplayer"],
    developmentTools: ["Unreal Engine", "Blender"],
    keyFeatures: [
      "Single Player",
      "Horror Atmosphere",
      "Stealth Mechanics",
    ],
    description:
      "A horror game built in Unreal Engine 5 for my CS415 Game Development course. Set in the haunted Grainger Engineering Library, you play as a student trapped in a nightmare, hunted by the menacing Grainger Bob. To escape, you must collect 14 scattered notes and pass your final exam—all while evading Bob’s pursuit using stealth and strategy.",
    tags: ["Unreal Engine", "Blender", "AI"],
    cardImgSrc: "/game-dev-projects/midnight-cram2.png",
    mediaContent: [
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    coreMechanicsContent: [
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    summary:
      "The Midnight Cram is a thrilling zombie-themed shooter designed to deliver intense action and horror gameplay. Set in a dark, atmospheric world, players battle hordes of zombies while unraveling a compelling story. The game’s narrative is driven by missions that immerse players in a chilling survival experience. Players must manage resources, fight terrifying enemies, and make decisions that impact the outcome of the story. Developed with Unity, the game combines intense combat sequences with a rich narrative to create a heart-pounding, story-driven experience that keeps players on the edge of their seats throughout.",
    designGoals: [
      "Create a tense and immersive horror atmosphere.",
      "Deliver high-intensity action gameplay.",
      "Develop a compelling, story-driven experience.",
    ],
    coreMechanic: [
      "Implemented player movement features, including a hiding mechanic that allows the player to take cover under tables to evade the AI enemy",
      "Built an inventory system enabling item usage such as a flashlight, batteries, and energy boosts for sprinting",
      "Designed and built one of the game’s levels, placing assets to craft a tense, immersive horror atmosphere",
      "Debugged issues with the AI pursuer logic to ensure consistent enemy behavior and proper chasing triggers",
    ],
    whatWentWell: [
      "The horror atmosphere was praised for its intensity.",
      "Action gameplay felt exciting and immersive.",
    ],
    challenges: [
      "Maintaining tension while keeping action engaging.",
      "Balancing the horror elements with gameplay progression.",
    ],
    lessonsLearned: [
      "Tension in horror gameplay is essential to player immersion.",
      "Action pacing needs to flow well with horror themes.",
    ],
  },
  "househould-hustle`": {
    projectName: "Household Hustle",
    linkText: "Link",
    link: "https://aashish-subramanian.itch.io/the-midnight-cram",
    role: ["Level Designer", "Artist"],
    genre: ["Combat", "Action", "Multiplayer"],
    developmentTools: ["Unreal Engine 5", "Blender"],
    keyFeatures: [
      "Open-world exploration",
      "Fantasy-themed environments",
      "Multiple quest lines",
    ],
    description:
      "description ecnldcm ldemclekdcm elkdcm elkdcm ledkcm eldkc meldkmc lked clke",
    tags: ["fantasy", "rpg", "open-world"],
    cardImgSrc: "/game-dev-projects/shifter2.png",
    mediaContent: [
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    coreMechanicsContent: [
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    summary:
      "Fantasy Quest is an open-world RPG set in a rich fantasy world filled with adventure, exploration, and quests. Players take on the role of a hero embarking on a journey through diverse landscapes, from lush forests to ancient ruins. With multiple quest lines, the game offers varied gameplay experiences, allowing players to choose their path while immersing themselves in the lore and history of the world. The game features a wide range of activities, including combat, puzzle-solving, and interaction with NPCs, creating a dynamic, engaging experience in a detailed, fantasy-driven environment.",
    designGoals: [
      "Create a vast, open-world environment.",
      "Develop a variety of quests for diverse playstyles.",
      "Ensure a compelling fantasy setting.",
    ],
    coreMechanic: [
      " ", 
      " ", 
      " "],
    whatWentWell: [
      "The world design was vast and engaging.",
      "Quest diversity appealed to a wide range of players.",
    ],
    challenges: [
      "Managing the scale of the open world.",
      "Ensuring quests felt meaningful within the world.",
    ],
    lessonsLearned: [
      "Open-world games need careful pacing to avoid overwhelming players.",
      "Quests should complement the world, not disrupt immersion.",
    ],
  },
  "ariadnes-blessing": {
    projectName: "Ariadne's Blessing",
    linkText: "Link to game",
    link: "https://github.com/AashishSubramanian26",
    role: ["Game Designer", "Artist"],
    genre: ["Combat", "Action", "Multiplayer"],
    developmentTools: ["Unreal Engine 4", "Blender"],
    keyFeatures: [
      "Last-player-standing mechanics",
      "Large multiplayer maps",
      "Real-time combat",
    ],
    description:
      "description ecnldcm ldemclekdcm elkdcm elkdcm ledkcm eldkc meldkmc lked clke",
    tags: ["battle royale", "multiplayer", "action"],
    cardImgSrc: "/game-dev-projects/shifter2.png",
    mediaContent: [
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    coreMechanicsContent: [
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    summary:
      "Battle Royale is an intense multiplayer action game where players compete for survival in a large, shrinking battlefield. The last-player-standing mechanic is at the core of the game, with players scavenging for resources, engaging in real-time combat, and avoiding elimination. The game offers large maps, dynamic environments, and fast-paced combat that rewards strategy and quick thinking. Developed using Unreal Engine 4, Battle Royale creates an adrenaline-pumping experience where players must outlast their opponents and be the last survivor. The game emphasizes teamwork, survival, and tactical combat for an exciting multiplayer experience.",
    designGoals: [
      "Create large, dynamic multiplayer maps.",
      "Ensure tight and engaging real-time combat.",
      "Focus on a fair and competitive gameplay experience.",
    ],
    coreMechanic: "Survival and combat in large multiplayer environments.",
    whatWentWell: [
      "Real-time combat was engaging and intense.",
      "The map design allowed for strategic gameplay.",
    ],
    challenges: [
      "Balancing player engagement throughout the game.",
      "Ensuring fair matchmaking for competitive play.",
    ],
    lessonsLearned: [
      "Game balance is crucial in battle royale games.",
      "Map design should cater to diverse playstyles and strategies.",
    ],
  },
  "sugar-and-slice": {
    projectName: "Sugar and Slice",
    linkText: "Link to game",
    link: "https://github.com/AashishSubramanian26",
    role: ["Game Designer", "Artist"],
    genre: ["Combat", "Action", "Multiplayer"],
    developmentTools: ["Unreal Engine 4", "Blender"],
    keyFeatures: [
      "Last-player-standing mechanics",
      "Large multiplayer maps",
      "Real-time combat",
    ],
    description:
      "description ecnldcm ldemclekdcm elkdcm elkdcm ledkcm eldkc meldkmc lked clke",
    tags: ["battle royale", "multiplayer", "action"],
    cardImgSrc: "/game-dev-projects/shifter2.png",
    mediaContent: [
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    coreMechanicsContent: [
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
      // "../src/images/game-dev-projects/visiongrunt.mov",
      "/game-dev-projects/beetle-bistro2.png",
      "/game-dev-projects/midnight-cram2.png",
    ],
    summary:
      "Battle Royale is an intense multiplayer action game where players compete for survival in a large, shrinking battlefield. The last-player-standing mechanic is at the core of the game, with players scavenging for resources, engaging in real-time combat, and avoiding elimination. The game offers large maps, dynamic environments, and fast-paced combat that rewards strategy and quick thinking. Developed using Unreal Engine 4, Battle Royale creates an adrenaline-pumping experience where players must outlast their opponents and be the last survivor. The game emphasizes teamwork, survival, and tactical combat for an exciting multiplayer experience.",
    designGoals: [
      "Create large, dynamic multiplayer maps.",
      "Ensure tight and engaging real-time combat.",
      "Focus on a fair and competitive gameplay experience.",
    ],
    coreMechanic: [
      " ", 
      " ", 
      " "],
    whatWentWell: [
      "Real-time combat was engaging and intense.",
      "The map design allowed for strategic gameplay.",
    ],
    challenges: [
      "Balancing player engagement throughout the game.",
      "Ensuring fair matchmaking for competitive play.",
    ],
    lessonsLearned: [
      "Game balance is crucial in battle royale games.",
      "Map design should cater to diverse playstyles and strategies.",
    ],
  },
};
